name: Run Selenium Tests with Headless Chrome

on:
  push:
    branches:
      - main  # Trigger action for PRs targeting the main branch
      - 'feature/*'  # Trigger for any feature branch as well
  pull_request:
    branches:
      - main  # Trigger for PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository code
      - name: Checkout current repository code
        uses: actions/checkout@v2

      # Checkout the repository containing the tests
      - name: Checkout the automation repository
        uses: actions/checkout@v2
        with:
          repository: "AbhishekTDigital/automation"
          path: automation  # Clone the automation repository in the "automation" directory

      # Set up Java (Maven needs JDK to run)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Specify distribution like AdoptOpenJDK or Zulu

      # Cache Maven dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install dependencies and start the React app (or your app)
      - name: Install dependencies and start React app
        run: |
          cd automation  # Navigate into the "automation" repo
          npm install  # Install dependencies (you may need to install npm if not present)
          npm run dev &  # Run the React app in the background (or your app's start command)

      # Wait for the server to start (or use a tool like `wait-on` to ensure it's available)
      - name: Wait for server to be ready
        run: |
          sleep 15  # Wait for 10 seconds for the app to start, adjust as necessary

      # Set up Headless Chrome using google-chrome-stable and chromedriver
      - name: Set up Headless Chrome and ChromeDriver
        run: |
          # Install dependencies
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
          sudo apt-get install -y libx11-dev libgdk-pixbuf2.0-0 libnspr4 libnss3

          # Set CHROME_BIN and CHROMEDRIVER_PATH for selenium
          export CHROME_BIN=/usr/bin/google-chrome-stable
          export CHROMEDRIVER_PATH=/usr/lib/chromium-browser/chromedriver

      # Run Selenium tests using Maven in the "automation" directory
      - name: Compile and run FirstPage
        run: |
          cd automation  # Navigate into the "automation" repo
          mvn clean test

      # Fail the workflow if tests fail
      - name: Check test results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed. Exiting workflow."
            exit 1
          fi
        shell: bash
