name: Run Selenium Tests

on:
  push:
    branches:
      - main  # Trigger action for PRs targeting the main branch
      - 'feature/*'  # Trigger for any feature branch as well
  pull_request:
    branches:
      - main  # Trigger for PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository code
      - name: Checkout current repository code
        uses: actions/checkout@v2

      # Checkout the repository containing the tests
      - name: Checkout the automation repository
        uses: actions/checkout@v2
        with:
          repository: "AbhishekTDigital/automation"
          path: automation  # Clone the automation repository in the "automation" directory

      # Set up Java (Maven needs JDK to run)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Specify distribution like AdoptOpenJDK or Zulu

      # Cache Maven dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Compile and run the specific test (FirstPageTest.class)
      - name: Compile and run FirstPageTest
        run: |
          cd automation  # Navigate into the "automation" repo
          mvn clean test -Dtest=React_App.Testing.FirstPageTest  # Compile and run the specific test

      # Fail the workflow if tests fail
      - name: Check test results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed. Exiting workflow."
            exit 1
          fi
        shell: bash
